spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project-r
    username: postgres
    password: batata123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
